name: network_monitor
description: "SIM and cellular network monitor for Aurora OS."
organization: "ru.networkmonitor"
license: "Proprietary"
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ^3.11.1
  flutter: ">=3.41.4"

dependencies:
  flutter:
    sdk: flutter
  device_info_plus:
    hosted:
      name: device_info_plus
      url: https://sdk-repo.omprussia.ru/sdk/flutter/pub/
  device_info_plus_aurora:
    hosted:
      name: device_info_plus_aurora
      url: https://sdk-repo.omprussia.ru/sdk/flutter/pub/
  device_info_plus_platform_interface:
    hosted:
      name: device_info_plus_platform_interface
      url: https://sdk-repo.omprussia.ru/sdk/flutter/pub/
  flutter_local_notifications:
    hosted:
      name: flutter_local_notifications
      url: https://sdk-repo.omprussia.ru/sdk/flutter/pub/
  workmanager:
    hosted:
      name: workmanager
      url: https://sdk-repo.omprussia.ru/sdk/flutter/pub/
  dbus:
    hosted:
      name: dbus
      url: https://sdk-repo.omprussia.ru/sdk/flutter/pub/

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
