name: network_monitor
description: "SIM and cellular network monitor for Aurora OS."
organization: "ru.networkmonitor"
license: "Proprietary"
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: 12.3.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
